# Generated by Django 4.2.4 on 2023-09-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
            ],
        ),
    ]
